### ISSUE TITLE
AttributeError when importing cce_backward_kernel

### ISSUE THREAD

**Issue by NiuMa-1234** [apple/ml-cross-entropy#6]
Thank you for your wonderful job! I've been trying to reproduce the results but encountered an error, could you please help me ?The error happened at the importing stage and below is the detailed information:

```
[rank7]:     from cut_cross_entropy import linear_cross_entropy
[rank7]:   File "/opt/conda/lib/python3.10/site-packages/cut_cross_entropy/__init__.py", line 2, in <module>
[rank7]:     from cut_cross_entropy.linear_cross_entropy import (
[rank7]:   File "/opt/conda/lib/python3.10/site-packages/cut_cross_entropy/linear_cross_entropy.py", line 20, in <module>
[rank7]:     from cut_cross_entropy.cce import cce_linear_cross_entropy
[rank7]:   File "/opt/conda/lib/python3.10/site-packages/cut_cross_entropy/cce.py", line 7, in <module>
[rank7]:     from cut_cross_entropy.cce_backward import cce_backward_kernel
[rank7]:   File "/opt/conda/lib/python3.10/site-packages/cut_cross_entropy/cce_backward.py", line 81, in <module>
[rank7]:     def _cce_backward_kernel(
[rank7]:   File "/opt/conda/lib/python3.10/site-packages/triton/runtime/jit.py", line 882, in jit
[rank7]:     return decorator(fn)
[rank7]:   File "/opt/conda/lib/python3.10/site-packages/triton/runtime/jit.py", line 871, in decorator
[rank7]:     return JITFunction(
[rank7]:   File "/opt/conda/lib/python3.10/site-packages/triton/runtime/jit.py", line 717, in __init__
[rank7]:     self.src = self.src[re.search(r"^def\s+\w+\s*\(", self.src, re.MULTILINE).start():]
[rank7]: AttributeError: 'NoneType' object has no attribute 'start
```

And I found the self.src of this function(_cce_backward_kernel) is not its content but its decorator...

Would this relate to the conda environment?  Any reply would be appreciated :D

**Comment by BangguWu** [comment]
I met the same problem, do you solved it?

**Comment by erikwijmans** [comment]
What version of triton are you using? I think I have seen this before on older versions of triton.

**Comment by NiuMa-1234** [comment]
> I met the same problem, do you solved it? \n (I also saw your issue in triton.)

No, I haven't...

**Comment by NiuMa-1234** [comment]
> What version of triton are you using? I think I have seen this before on older versions of triton.

Hi, the version of the triton I use is 3.1.0, and my cuda version is 12.4, GPU: A800-SXM ,PyTorch: 2.5.1 , python: 3.10.9

**Comment by andersonbcdefg** [comment]
I am also getting this issue.
Python 3.10.8
triton==3.0.0
torch==2.5.0.dev20240912+cu124
H100 GPU

**Comment by erikwijmans** [comment]
I cannot seem to reproduce this on my end. Does `python -c "from cut_cross_entropy import linear_cross_entropy"` work? Maybe deespeed or torchrun is causing different versions to be picked up?

**Comment by erikwijmans** [comment]
Also, looking quickly a the issue opened on Triton,
```python
_cce_backward_kernel = cce_backward_autotune()(_cce_backward_kernel)
_cce_backward_kernel = triton.heuristics(...)(_cce_backward_kernel)
_cce_backward_kernel = triton.jit(_cce_backward_kernel)
```
is not quite right. Decorators are applied in reverse order, so the equivalent code is
```python
_cce_backward_kernel = triton.jit(_cce_backward_kernel)
_cce_backward_kernel = triton.heuristics(...)(_cce_backward_kernel)
_cce_backward_kernel = cce_backward_autotune()(_cce_backward_kernel)
```

Not sure if this is related, but any code changes that would cause the order the decorators get applied to be swapped would cause issues.

**Comment by erikwijmans** [comment]
What does `TRITON_INTERPRET=1 python -c "from cut_cross_entropy.cce_backward import _cce_backward_kernel; import inspect; print(inspect.getsource(_cce_backward_kernel.fn.fn.fn))"` show.

Doing `TRITON_INTERPRET=1` should cause the error to not happen as that uses a different code path in Triton for just debugging.

**Comment by NiuMa-1234** [comment]
> What does `TRITON_INTERPRET=1 python -c "from cut_cross_entropy.cce_backward import _cce_backward_kernel; import inspect; print(inspect.getsource(_cce_backward_kernel.fn.fn.fn))"` show?
> 
> Doing `TRITON_INTERPRET=1` should cause the error to not happen as that uses a different code path in Triton for just debugging.

It shows like this:
```
@cce_backward_autotune()
@triton.heuristics(
    {
        "EVEN_D": lambda args: (args["D"] % args["BLOCK_D"]) == 0,
        "MM_BACK_BLOCK_D": lambda args: args["BLOCK_D"] * 2,
        "MM_BACK_EVEN_D": lambda args: (args["D"] % (args["BLOCK_D"] * 2)) == 0,
        "HAS_VALIDS": lambda args: args["Valids"] is not None,
        "HAS_VOCAB_ORDERING": lambda args: args["VocabOrdering"] is not None,
        "FILTER_GRAD": lambda args: args["filter_eps"] is not None,
        "HAS_TARGETS": lambda args: args["Targets"] is not None,
        "HAS_SOFTCAP": lambda args: args["softcap"] is not None,
        "ITEM_DO": lambda args: args["dOut"].numel() == 1,
        "GROUP_B": lambda args: 8,
    }
)
```

**Comment by NiuMa-1234** [comment]
> What does `TRITON_INTERPRET=1 python -c "from cut_cross_entropy.cce_backward import _cce_backward_kernel; import inspect; print(inspect.getsource(_cce_backward_kernel.fn.fn.fn))"` show?
> 
> Doing `TRITON_INTERPRET=1` should cause the error to not happen as that uses a different code path in Triton for just debugging.

Moreover, I tried temporarily banning the backward in linear_cross_entropy and test the cuda time of cce's fwd, and found it takes more time than the orig loss. would this result be normal (or the backward function must be involved)?

Here's the cuda time of original loss, which takes 20us:
![image](https://github.com/user-attachments/assets/52cd636f-2cec-4978-a746-5d49f517e44d)

And here's the cce's with no bad func, which takes 70us:
![image](https://github.com/user-attachments/assets/938f471d-ad5d-4178-9a48-d29809c73987)

**Comment by erikwijmans** [comment]
> 
> It shows like this:
> 
> ```
> @cce_backward_autotune()
> @triton.heuristics(
>     {
>         "EVEN_D": lambda args: (args["D"] % args["BLOCK_D"]) == 0,
>         "MM_BACK_BLOCK_D": lambda args: args["BLOCK_D"] * 2,
>         "MM_BACK_EVEN_D": lambda args: (args["D"] % (args["BLOCK_D"] * 2)) == 0,
>         "HAS_VALIDS": lambda args: args["Valids"] is not None,
>         "HAS_VOCAB_ORDERING": lambda args: args["VocabOrdering"] is not None,
>         "FILTER_GRAD": lambda args: args["filter_eps"] is not None,
>         "HAS_TARGETS": lambda args: args["Targets"] is not None,
>         "HAS_SOFTCAP": lambda args: args["softcap"] is not None,
>         "ITEM_DO": lambda args: args["dOut"].numel() == 1,
>         "GROUP_B": lambda args: 8,
>     }
> )
> ```

That is very confusing. I am not sure what would cause that to happen. I can't reproduce this on my end so it is very hard to figure out what is going. It almost looks like python is applying the decorators in the wrong order, but I have never seen that. Are you on WSL by chance? I have seen odd things happen there but in on other contexts.

**Comment by erikwijmans** [comment]
> Moreover, I temporarily commented out the backward in linear_cross_entropy and test the cuda time of cce's fwd, and found it takes more time than the original loss. would this result be normal (or the backward function must be involved)?


That seems fine. The kernels are tuned for more normal matrix dimensions, not the tiny ones used in the unit tests.

**Comment by NiuMa-1234** [comment]
> > It shows like this:
> > ```
> > @cce_backward_autotune()
> > @triton.heuristics(
> >     {
> >         "EVEN_D": lambda args: (args["D"] % args["BLOCK_D"]) == 0,
> >         "MM_BACK_BLOCK_D": lambda args: args["BLOCK_D"] * 2,
> >         "MM_BACK_EVEN_D": lambda args: (args["D"] % (args["BLOCK_D"] * 2)) == 0,
> >         "HAS_VALIDS": lambda args: args["Valids"] is not None,
> >         "HAS_VOCAB_ORDERING": lambda args: args["VocabOrdering"] is not None,
> >         "FILTER_GRAD": lambda args: args["filter_eps"] is not None,
> >         "HAS_TARGETS": lambda args: args["Targets"] is not None,
> >         "HAS_SOFTCAP": lambda args: args["softcap"] is not None,
> >         "ITEM_DO": lambda args: args["dOut"].numel() == 1,
> >         "GROUP_B": lambda args: 8,
> >     }
> > )
> > ```
> 
> That is very confusing. I am not sure what would cause that to happen. I can't reproduce this on my end so it is very hard to figure out what is going. It almost looks like python is applying the decorators in the wrong order, but I have never seen that. Are you on WSL by chance? I have seen odd things happen there but in on other contexts.

No, mine is just linux, Debian GNU/Linux

**Comment by NiuMa-1234** [comment]
> > Moreover, I temporarily commented out the backward in linear_cross_entropy and test the cuda time of cce's fwd, and found it takes more time than the original loss. would this result be normal (or the backward function must be involved)?
> 
> That seems fine. The CCE kernels are tuned for more normal matrix dimensions, not the tiny ones used in the unit tests.

Yes, you're right. I scaled up the size of samples from 256  to 8192, then the speed of cce observably surpassed the original CE by 4 times. That's really brilliant. Thank you for your contribution. (And I truly wish to be able to use its bwd function...)

**Comment by erikwijmans** [comment]
That is very odd that you can use the forward function but not the backward, despite both using the same setup of decorators. One idea, can you try commenting out the 3 decorators on `_cce_backward_kernel` and then after that function is declared (so here https://github.com/apple/ml-cross-entropy/blob/main/cut_cross_entropy/cce_backward.py#L236) adding

```python

_cce_backward_kernel = triton.jit(_cce_backward_kernel)
_cce_backward_kernel = triton.heuristics(
    {
        "EVEN_D": lambda args: (args["D"] % args["BLOCK_D"]) == 0,
        "MM_BACK_BLOCK_D": lambda args: args["BLOCK_D"] * 2,
        "MM_BACK_EVEN_D": lambda args: (args["D"] % (args["BLOCK_D"] * 2)) == 0,
        "HAS_VALIDS": lambda args: args["Valids"] is not None,
        "HAS_VOCAB_ORDERING": lambda args: args["VocabOrdering"] is not None,
        "FILTER_GRAD": lambda args: args["filter_eps"] is not None,
        "HAS_TARGETS": lambda args: args["Targets"] is not None,
        "HAS_SOFTCAP": lambda args: args["softcap"] is not None,
        "ITEM_DO": lambda args: args["dOut"].numel() == 1,
        "GROUP_B": lambda args: 8,
    }
)(_cce_backward_kernel)

_cce_backward_kernel = cce_backward_autotune()(cce_backward_autotune)
```

**Comment by andersonbcdefg** [comment]
I get the error in the most simple setup I can think of: fresh install of only this package, attempt to import linear_cross_entropy, error happens. I did not make any modifications to your code.

python version 3.10, installed packages are:
triton==3.1.0
torch==2.5.1

I tested this on a GPU from Modal Labs, with the following code:

```
import modal

image = modal.Image.debian_slim(python_version="3.10").apt_install("git").pip_install(
    "cut-cross-entropy @ git+https://github.com/apple/ml-cross-entropy.git"
)

app = modal.App("cut-cross-entropy")

@app.function(
    image=image,
    gpu=modal.gpu.A10G()
)
def test_cce():
    from cut_cross_entropy import linear_cross_entropy
    print("success!")
```

Backtrace:
```
Traceback (most recent call last):
  File "/root/test.py", line 14, in test_cce
    from cut_cross_entropy import linear_cross_entropy
  File "/usr/local/lib/python3.10/site-packages/cut_cross_entropy/__init__.py", line 2, in <module>
    from cut_cross_entropy.linear_cross_entropy import (
  File "/usr/local/lib/python3.10/site-packages/cut_cross_entropy/linear_cross_entropy.py", line 20, in <module>
    from cut_cross_entropy.cce import cce_linear_cross_entropy
  File "/usr/local/lib/python3.10/site-packages/cut_cross_entropy/cce.py", line 7, in <module>
    from cut_cross_entropy.cce_backward import cce_backward_kernel
  File "/usr/local/lib/python3.10/site-packages/cut_cross_entropy/cce_backward.py", line 81, in <module>
    def _cce_backward_kernel(
  File "/usr/local/lib/python3.10/site-packages/triton/runtime/jit.py", line 882, in jit
    return decorator(fn)
  File "/usr/local/lib/python3.10/site-packages/triton/runtime/jit.py", line 871, in decorator
    return JITFunction(
  File "/usr/local/lib/python3.10/site-packages/triton/runtime/jit.py", line 717, in __init__
    self.src = self.src[re.search(r"^def\s+\w+\s*\(", self.src, re.MULTILINE).start():]
AttributeError: 'NoneType' object has no attribute 'start'
```

**Comment by erikwijmans** [comment]
Sorry for the typo! Fixed the comment above.

This feels more like a python bug than a triton bug honestly. Decorators are just syntactic sugar that should result in the same logical code as the fix. It's also very odd that this issue only exists for the backward kernel, despite the forward kernel and the indexed matmul kernel using the same pattern.

**Comment by andersonbcdefg** [comment]
Agree, but the problem comes from Triton inspecting the source with a
regexp so you could also blame them for doing that. 😅 And yeah, I dunno
enough about Triton to understand why it happens to one kernel but not the
others. I'm just a regular guy trying to save a ton of memory training my
BERT 😄
